apiVersion: v1
kind: Secret
metadata:
  name: my-docker-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJXRmthR0YyWkc5amEyVnlNVEl6T21SamEzSmZjR0YwWHpaR09XNDBabGN5UmpreWVtRXRWR3MyZFZGUWJsQTVlSGxGTUE9PSIKCQl9Cgl9Cn0=








